name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    
    - name: Create conda environment
      run: conda env create -f env.yml
    
    - name: Install iqc
      run: conda run -n iqc-env pip install -e .
    
    - name: Install test dependencies
      run: conda run -n iqc-env pip install pytest pytest-cov
    
    - name: Run tests
      run: conda run -n iqc-env pytest iqc/tests/ --cov=iqc --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 